# Generated by Django 3.1.7 on 2022-01-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
